name: Python Scraper CI

on:
  push:
    paths:
      - 'scraper-python/**'
  pull_request:
    paths:
      - 'scraper-python/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r scraper-python/requirements.txt

      - name: Run tests
        run: pytest scraper-python/tests
